[package]
name = "egui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.25"
calamine = "0.18"
umya-spreadsheet = "2.0.1"


eframe = "0.26.2"

env_logger = {version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
]}